export const NomenclatureConstants = [
    {nr: 1, title: 'Substante active', name: 'activeSubstance'},
    {nr: 2, title: 'Coduri ATC', name: 'atcCodes'},
    {nr: 3, title: 'Autorizatii', name: 'autorization'},
    {nr: 4, title: 'Substante auxiliare', name: 'auxiliarySubstance'},
    {nr: 5, title: 'Conturi bancare', name: 'bankAccount'},
    {nr: 6, title: 'Banci', name: 'bank'},
    {nr: 7, title: 'Fazele studiilor clinice', name: 'clinicalTrailPhase'},
    {nr: 8, title: 'Tari', name: 'country'},
    {nr: 9, title: 'Grupuri de tari', name: 'countryGroup'},
    {nr: 10, title: 'Valute', name: 'currency'},
    {nr: 11, title: 'Istoricul valutar', name: 'currencyHistory'},
    {nr: 12, title: 'Coduri vamale', name: 'customsCode'},
    {nr: 13, title: 'Grupuri vamale', name: 'customsGroup'},
    {nr: 14, title: 'Puncte vamale', name: 'customsPoint'},
    {nr: 15, title: 'Tipuri de documente', name: 'documentType'},
    {nr: 16, title: 'Arhiva de documente', name: 'documentArchive'},
    {nr: 17, title: 'Conturi bancare ale agentilor economici', name: 'economicAgentBankAccount'},
    {nr: 18, title: 'Informatii de contact ale agentilor economici', name: 'economicAgentContactInfo'},
    {nr: 19, title: 'Tipurile de agenti economici', name: 'economicAgentType'},
    {nr: 20, title: 'Agenti economici', name: 'economicAgent'},
    {nr: 21, title: 'Lista de angajati', name: 'employees'},
    {nr: 22, title: 'Identificatori de tipuri de documente', name: 'identificationDocumentType'},
    {nr: 23, title: 'Denumirile internationale ale medicamentelor', name: 'internationalMedicamentName'},
    {nr: 24, title: 'Investigatori', name: 'investigator'},
    {nr: 25, title: 'Etichete', name: 'label'},
    {nr: 26, title: 'Localitati', name: 'locality'},
    {nr: 27, title: 'Conturile bancare ale producatorilor', name: 'manufactureBankAccount'},
    {nr: 28, title: 'Producatori de medicamente', name: 'manufacture'},
    {nr: 29, title: 'Institutii medicale', name: 'medicalInstitution'},
    {nr: 30, title: 'Forme medicale', name: 'medicalForm'},
    {nr: 31, title: 'Grupe medicale', name: 'medicalGroup'},
    {nr: 32, title: 'Tipuri de medicamente', name: 'medicalType'},
    {nr: 33, title: 'Organizatii', name: 'organization'},
    {nr: 34, title: 'Conturi bancare ale organizatiilor', name: 'organizationBankAccount'},
    {nr: 35, title: 'Parteneri', name: 'partner'},
    {nr: 36, title: 'Tipuri de forme farmaceutice', name: 'pharmaceuticalFormType'},
    {nr: 37, title: 'Forme farmaceutice', name: 'pharmaceuticalForm'},
    {nr: 38, title: 'Tipuri de preturi', name: 'priceType'},
    {nr: 39, title: 'Preturi', name: 'price'},
    {nr: 40, title: 'Profesii', name: 'profession'},
    {nr: 41, title: 'Regiuni', name: 'state'},
    {nr: 42, title: 'Subdiviziuni', name: 'subdivision'},
    {nr: 43, title: 'Taxe', name: 'tax'},
    {nr: 44, title: 'Arhiva de trafic', name: 'trafficArchive'},
    {nr: 45, title: 'Tipuri de activitati farmaceutice', name: 'typeOfPharmacyActivity'},
    {nr: 46, title: 'Tipri de tranzactii vamale', name: 'typeOfCustomsTransactions'},
    {nr: 47, title: 'Tipri de modificari ale drogurilor', name: 'typeOfDrugChanges'},
    {nr: 48, title: 'Unitati de masura', name: 'unitsOfMeasurement'},
    {nr: 49, title: 'Variatiile tipurilor de cereri', name: 'variationRequestType'},
    {nr: 50, title: 'Substante psihotrope autorizate', name: 'authorizedDrugSubstances'},
    {nr: 51, title: 'Taxe de servicii', name: 'serviceCharges'},
    {nr: 52, title: 'Medicamente biologice', name: 'nm_biological_medicines'},
    {nr: 53, title: 'Fabricație', name: 'nm_gmp_manufacture'},
    {nr: 54, title: 'Produse nesterile pentru investigație', name: 'nm_nesterile_products'},
    {nr: 55, title: 'Ambalare primara', name: 'nm_primary_packaging'},
    {nr: 56, title: 'Ambalare secundara', name: 'nm_secondary_packaging'},
    {nr: 57, title: 'Tipuri de sterilizare a substanţelor', name: 'nm_sterilizations'},
    {nr: 58, title: 'Teste pentru controlul calităţii', name: 'nm_tests_for_quality_control'},
    {nr: 59, title: 'Categorii de audit', name: 'nm_audit_category'},
    {nr: 60, title: 'Subcategorii de audit', name: 'nm_audit_subcategory'},
    {nr: 61, title: 'Activități de import', name: 'nm_import_activities'},
    {nr: 62, title: 'Statuturile utilizatorilor LDAP', name: 'nm_ldap_user_status'},
    {nr: 63, title: 'Codurile registrelor', name: 'nm_register_catalog_codes'},
    {nr: 64, title: 'Rata de conversie a unitatilor de masura pentru droguri', name: 'drug_units_conversion_rates'},
    {nr: 65, title: 'Rapoarte', name: 'nm_reports'},
    {nr: 66, title: 'Tipuri de rapoarte', name: 'nm_report_types'},
    {nr: 67, title: 'Subdiviziuni la institutii medicale', name: 'nm_med_inst_subdivisions'},
    {nr: 68, title: 'Secții', name: 'nm_departments'},
];
